apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-postgres
  namespace: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-postgres
  template:
    metadata:
      labels:
        app: calculator-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: calculator-postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: calculator-postgres-pvc
