apiVersion: v1
kind: Secret
metadata:
  name: calculator-postgres-secret
  namespace: calculator
type: Opaque
stringData:
  POSTGRES_DB: calculator
  POSTGRES_USER: calculator
  POSTGRES_PASSWORD: calculator123
