apiVersion: v1
kind: Service
metadata:
  name: calculator-postgres
  namespace: calculator
spec:
  clusterIP: None
  selector:
    app: calculator-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
